services:
  db:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: concert_ticket
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7.2.5-alpine
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - 16686:16686

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    ports:
      - 4317:4317
    depends_on:
      - jaeger
    volumes:
      - ./../otel-collector.yaml:/etc/otel-collector.yaml

volumes:
  db_data:
    driver: local